version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: panganku
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      DB_NAME: panganku_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: PanganKuJWTSecretKey2026VeryLongAndSecureForProduction
      AES_KEY: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      APP_PORT: 8080
      APP_ENV: development
      TELEGRAM_BOT_TOKEN: 8675400980:AAEz9kyZ42s6xSG8Gj9KjHLPNtX9Z5MnNPc
      TELEGRAM_CHAT_ID: "7661394746"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: panganku_db
      POSTGRES_USER: panganku
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U panganku"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1
    ports:
      - "6380:6379"

volumes:
  pgdata:

